export const usuarios = [
    {
      nombre: "admin",
      apellido: "admin",
      correo: "admin@mail.com",
      password: "admin",
      idCliente: 1,
      idPerfil: 1,
      idSucursal: 2,
    },
    {
      nombre: "isaac",
      apellido: "fierro",
      correo: "isaac@mail.com",
      password: "1234",
      idCliente: 1,
      idPerfil: 2,
      idSucursal: 2,
    },
    {
      nombre: "moises",
      apellido: "sandoval",
      correo: "moises@mail.com",
      password: "2345",
      idCliente: 1,
      idPerfil: 3,
      idSucursal: 1,
    },
    {
      nombre: "adan",
      apellido: "adan",
      correo: "adan@mail.com",
      password: "3456",
      idCliente: 1,
      idPerfil: 3,
      idSucursal: 2,
    },
    {
      nombre: "juan",
      apellido: "jimenex",
      correo: "juan@mail.com",
      password: "4567",
      idCliente: 1,
      idPerfil: 3,
      idSucursal: 2,
    },
    {
      nombre: "don",
      apellido: "jacinto",
      correo: "jacinto@mail.com",
      password: "jacinto123",
      idCliente: 1,
      idPerfil: 3,
      idSucursal: 2,
    },
  ];
  